version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
    - gunicorn
    - uploadprocessfile.wsgi:application
    - --bind
    - "0.0.0.0:8000"
    ports:
      - "8888:8000"
    depends_on:
      - 'redis'
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploadprocessfile/database:/app/database

  redis:
    image: "redis:latest"